services:
  db:
    image: mysql:8.0
    container_name: nextstop_db
    restart: always
    environment:
      MYSQL_DATABASE: NextStop
      MYSQL_USER: dbrian
      MYSQL_PASSWORD: 3aFW3e1Va50cou
      MYSQL_ROOT_PASSWORD: 2NJECc5R0jiB4d
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - nextstop_net

  backend:
    build: ./backend
    container_name: nextstop_backend
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=NextStop
      - DB_USER=dbrian
      - DB_PASSWORD=3aFW3e1Va50cou
      - DB_HOST=db
      - DB_PORT=3306
    networks:
      - nextstop_net

  frontend:
    build: ./frontend
    container_name: nextstop_frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - nextstop_net

networks:
  nextstop_net:

volumes:
  db_data:
