# Generated by Django 5.2.7 on 2025-10-27 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('url_base', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('TRANSPORTE', 'Transporte'), ('VUELO', 'Vuelo'), ('HOTEL', 'Hotel')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_recurso', models.CharField(choices=[('DESTINO', 'Destino'), ('HOTEL', 'Hotel'), ('ITINERARIO', 'Itinerario'), ('TRANSPORTE', 'Transporte')], max_length=10)),
                ('id_recurso_local', models.IntegerField(blank=True, null=True)),
                ('api_id', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_marcado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino_busqueda', models.CharField(max_length=255)),
                ('fecha_busqueda', models.DateTimeField(auto_now_add=True)),
                ('origen', models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Mobile')], max_length=6)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleItinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('DESTINO', 'Destino'), ('HOTEL', 'Hotel'), ('TRANSPORTE', 'Transporte')], max_length=10)),
                ('api_id', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_item', models.CharField(max_length=200)),
                ('origen', models.CharField(blank=True, max_length=255, null=True)),
                ('destinos', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('fecha_llegada', models.DateTimeField(blank=True, null=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('personas', models.IntegerField(default=1)),
                ('presupuesto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itinerarios.itinerario')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itinerarios.proveedorapi')),
            ],
        ),
    ]
