# Generated by Django 5.2.7 on 2025-10-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialbusqueda',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='detalleitinerario',
            name='costo_estimado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleitinerario',
            name='tipo_item',
            field=models.CharField(choices=[('DESTINO', 'Destino'), ('HOTEL', 'Hotel'), ('TRANSPORTE', 'Transporte')], max_length=12),
        ),
        migrations.DeleteModel(
            name='Favorito',
        ),
        migrations.DeleteModel(
            name='HistorialBusqueda',
        ),
    ]
