# Generated by Django 5.2.7 on 2025-11-12 02:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerarios', '0002_remove_historialbusqueda_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleitinerario',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleitinerario',
            name='dias',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='detalleitinerario',
            name='seleccionado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='detalleitinerario',
            name='itinerario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='itinerarios.itinerario'),
        ),
        migrations.AlterField(
            model_name='detalleitinerario',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itinerarios.proveedorapi'),
        ),
        migrations.AlterField(
            model_name='detalleitinerario',
            name='tipo_item',
            field=models.CharField(choices=[('DESTINO', 'Destino'), ('HOTEL', 'Hotel'), ('TRANSPORTE', 'Transporte'), ('ACTIVIDAD', 'Actividad')], max_length=15),
        ),
        migrations.AlterField(
            model_name='proveedorapi',
            name='tipo',
            field=models.CharField(choices=[('TRANSPORTE', 'Transporte'), ('VUELO', 'Vuelo'), ('HOTEL', 'Hotel'), ('ACTIVIDAD', 'Actividad')], max_length=15),
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('seleccionado', models.BooleanField(default=False)),
                ('detalle_itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='itinerarios.detalleitinerario')),
            ],
        ),
    ]
