# Generated by Django 5.2.7 on 2025-11-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerarios', '0003_detalleitinerario_creado_en_detalleitinerario_dias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedorapi',
            name='tipo',
            field=models.CharField(choices=[('VUELO', 'Vuelo'), ('HOTEL', 'Hotel'), ('ACTIVIDAD', 'Actividad')], max_length=15),
        ),
        migrations.AlterField(
            model_name='proveedorapi',
            name='url_base',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
