# Generated by Django 5.2.7 on 2025-11-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerarios', '0004_alter_proveedorapi_tipo_alter_proveedorapi_url_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleitinerario',
            name='tipo_item',
            field=models.CharField(choices=[('DESTINO', 'Destino'), ('HOTEL', 'Hotel'), ('ACTIVIDAD', 'Actividad')], max_length=15),
        ),
    ]
