# Generated by Django 5.2.7 on 2025-11-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerarios', '0005_alter_detalleitinerario_tipo_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleitinerario',
            name='tipo_item',
            field=models.CharField(choices=[('DESTINO', 'Destino'), ('HOTEL', 'Hotel'), ('TRANSPORTE', 'Transporte'), ('ACTIVIDAD', 'Actividad')], max_length=15),
        ),
    ]
