# Generated by Django 5.2.7 on 2025-11-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerarios', '0006_alter_detalleitinerario_tipo_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleitinerario',
            name='info_completa',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
