# Generated by Django 5.2.7 on 2025-10-27 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_remove_usuario_roles_alter_rol_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino_busqueda', models.CharField(max_length=255)),
                ('fecha_busqueda', models.DateTimeField(auto_now_add=True)),
                ('origen', models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Mobile')], max_length=6)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
