# Generated by Django 5.2.7 on 2025-10-27 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_remove_usuario_roles_alter_rol_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_recurso', models.CharField(choices=[('DESTINO', 'Destino'), ('HOTEL', 'Hotel'), ('ITINERARIO', 'Itinerario'), ('TRANSPORTE', 'Transporte')], max_length=12)),
                ('id_recurso_local', models.IntegerField(blank=True, null=True)),
                ('api_id', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_marcado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
