# Generated by Django 5.2.7 on 2025-10-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_roles_alter_rol_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
