# Generated by Django 5.2.7 on 2025-10-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_codigo_verificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password_hash',
            field=models.CharField(max_length=128),
        ),
    ]
