# Generated by Django 5.2.7 on 2025-11-03 03:13

import django.db.models.deletion
import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='codigo_verificacion',
        ),
        migrations.CreateModel(
            name='Verificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('expiracion', models.DateTimeField(default=usuarios.models.default_expiration)),
                ('usado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificaciones', to='usuarios.usuario')),
            ],
        ),
    ]
