# Generated by Django 5.2.7 on 2025-11-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_usuario_codigo_verificacion_verificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacion',
            name='codigo',
            field=models.CharField(max_length=4),
        ),
    ]
